package exercise5.hotelbeds;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.net.ssl.HttpsURLConnection;

import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;


public class CreateSignature {

	public static String apiKey = "n893ppz253mvrh7k7y7dghgq";
	public static String Secret = "6sr2JE73sX";
	public static String signature;
	public static Map<String,Object> headerMap = new HashMap<String,Object>();
	public static String firstBookableRoomRate;
	public static String bookingRef;
	@BeforeSuite
	public  void createSigature() throws IOException {

		try {
			// Your API Key and secret

			// Signature is generated by SHA256 (Api-Key + Secret +
			// Timestamp (in seconds))
			signature = org.apache.commons.codec.digest.DigestUtils
					.sha256Hex(apiKey + Secret + System.currentTimeMillis() / 1000);

			// Example of call to the API
			String endpoint = "https://api.test.hotelbeds.com/hotel-api/1.0/status";
			URL url = new URL(endpoint);

			HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
			connection.setRequestProperty("X-Signature", signature);
			connection.setRequestProperty("Api-Key", apiKey);
			connection.setRequestProperty("Accept", "application/json");

			System.out.println("Signature : " + signature);

		} catch (Exception e) {
			e.printStackTrace();
		}

		RestAssured.baseURI="https://api.test.hotelbeds.com/hotel-api/1.0/";

		headerMap.put("Api-key", apiKey);
		headerMap.put("X-Signature", signature);
		headerMap.put("Accept", "application/json");
		headerMap.put("Accept-Encoding", "gzip");
		headerMap.put("Content-Type", "application/json");



	}

}